clear_profile:
  name: Clear charging profiles
  description: Clears all charging profiles (limits) set (dependent on charger support)
  target:
    device:
      integration: "ocpp"

update_firmware:
  name: Update charger firmware
  description: Specify server to download firmware and time to delay updating (dependent on charger support), supported transfer protocols can be requested by the configuration key SupportedFileTransferProtocols
  fields:
    firmware_url:
      name: Url of firmware
      description: Full url of firmware file (http or https)
      required: true
      advanced: true
      example: "http://www.charger.com/firmware.bin"
    delay_hours:
      name: Delay hours
      description: Hours to delay charger update
      required: false
      advanced: true
      example: 12
      default: 0
      
configure:
  name: Configure charger features
  description: Change supported Ocpp v1.6 configuration values
  fields:
    ocpp_key:
      name: Configuration key name 
      description: Write-enabled key name supported 
      required: true
      advanced: true
      example: "WebSocketPingInterval"
    value:
      name: Key value
      description: Value to write to key
      required: true
      advanced: true
      example: "60"
      
get_configuration:
  name: Get configuration values for charger
  description: Change supported Ocpp v1.6 configuration values
  fields:
    ocpp_key:
      name: Configuration key name 
      description: Key name supported 
      required: true
      advanced: true
      example: "WebSocketPingInterval"
      
get_diagnostics:
  name: Request diagnostic data from charger
  description: Specify server url to upload diagnostic data to (dependent on charger support), supported transfer protocols can be requested by the configuration key SupportedFileTransferProtocols
  fields:
    upload_url:
      name: Url for upload
      description: Full url to upload to
      required: true
      advanced: true
      example: "https://webhook.site/abc"